version: "3.4"
services:
  wager-api:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      timeout: 40s
      interval: 10s
      retries: 10
    # ports:
      # - "5432:5432"
    volumes:
      - ./postgres/1001_migrate.up.sql:/docker-entrypoint-initdb.d/init_db.sql



