// Code generated by mockgen. DO NOT EDIT.
package mock_repositories

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/wager-api/internal/entities"
	"github.com/wager-api/libs/database"
)

type MockPurchaseRepo struct {
	mock.Mock
}

func (r *MockPurchaseRepo) Create(arg1 context.Context, arg2 database.Ext, arg3 *entities.Purchase) error {
	args := r.Called(arg1, arg2, arg3)
	return args.Error(0)
}